# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  licenses: Apache-2.0
  images: |
    - name: alertmanager
      image: docker.io/bitnami/alertmanager:0.27.0-debian-12-r1
    - name: blackbox-exporter
      image: docker.io/bitnami/blackbox-exporter:0.24.0-debian-12-r25
    - name: prometheus
      image: docker.io/bitnami/prometheus:2.50.1-debian-12-r1
    - name: prometheus-operator
      image: docker.io/bitnami/prometheus-operator:0.72.0-debian-12-r1
    - name: thanos
      image: docker.io/bitnami/thanos:0.34.1-debian-12-r0
apiVersion: v2
appVersion: 0.72.0
dependencies:
- condition: exporters.enabled,exporters.node-exporter.enabled
  name: node-exporter
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 3.x.x
- condition: exporters.enabled,exporters.kube-state-metrics.enabled
  name: kube-state-metrics
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 3.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Prometheus Operator provides easy monitoring definitions for Kubernetes services and deployment and management of Prometheus instances.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/prometheus-operator/img/prometheus-operator-stack-220x234.png
keywords:
- prometheus
- alertmanager
- operator
- monitoring
kubeVersion: '>= 1.16.0-0'
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: kube-prometheus
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/kube-prometheus
version: 8.30.1
